spring:
    profile:
        active: dev
        
---
spring:
    profile: dev
    application:
        name: cloud-config-dev
      
---
spring:
    profile: test
    application:
        name: cloud-config-test